# Generated by Django 4.0.3 on 2022-05-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_books_user_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
