# Generated by Django 4.0.3 on 2022-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(help_text='Выберите книги', to='myapp.book'),
        ),
    ]
