# Generated by Django 4.0.3 on 2022-07-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Edit book'),)},
        ),
    ]
